workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Generate Android Folder and Build APK
        script: |
          # توليد مجلد الأندرويد للمشاريع العادية إذا لم يكن موجودا
          if [ ! -d "android" ]; then
            npx react-native eject --no-install || npx react-native @react-native-community/cli android
          fi
          # الدخول لبدأ التجميع المستقر
          cd android && ./gradlew assembleRelease
