workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: latest
    scripts:
      - name: Install and Build Android
        script: |
        # تثبيت الحزم و المشغل الرسمي
          npm install
          npm install -g react-native-cli

          # إنشاء مجلد أندرويد قياسي متوافق متكامل
          npx react-native@0.71.0 init TemporaryApp --template react-native-template-typescript --skip-install
          cp -r TemporaryApp/Android ./android

          # بدأالبناء و التجميع النهائي
          cd android && ./gradlew assembleRelease
