WITH new_b(wcode, name_fr, name_ar) AS (VALUES
('16','Alger Centre','الجزائر الوسطى'),('16','Sidi M''Hamed','سيدي امحمد'),('16','El Madania','المدنية'),('16','Belouizdad','بلوزداد'),('16','Bab El Oued','باب الوادي'),('16','Bologhine','بولوغين'),('16','Casbah','القصبة'),('16','Oued Koriche','وادي قريش'),('16','Bir Mourad Rais','بئر مراد رايس'),('16','El Biar','الأبيار'),('16','Bouzareah','بوزريعة'),('16','Birkhadem','بئر خادم'),('16','El Harrach','الحراش'),('16','Baraki','براقي'),('16','Oued Smar','وادي السمار'),('16','Bourouba','بوروبة'),('16','Hussein Dey','حسين داي'),('16','Kouba','القبة'),('16','Bachdjerrah','باش جراح'),('16','Dar El Beida','الدار البيضاء'),('16','Bab Ezzouar','باب الزوار'),('16','Ben Aknoun','بن عكنون'),('16','Dely Ibrahim','دالي إبراهيم'),('16','El Hammamet','الحمامات'),('16','Rais Hamidou','الرايس حميدو'),('16','Djasr Kasentina','جسر قسنطينة'),('16','El Mouradia','المرادية'),('16','Hydra','حيدرة'),('16','Mohammadia','المحمدية'),('16','Bordj El Kiffan','برج الكيفان'),('16','El Magharia','المقرية'),('16','Beni Messous','بني مسوس'),('16','Les Eucalyptus','الكاليتوس'),('16','Birtouta','بئر توتة'),('16','Tessala El Merdja','تسالة المرجة'),('16','Ouled Chebel','أولاد شبل'),('16','Sidi Moussa','سيدي موسى'),('16','Ain Taya','عين طاية'),('16','Bordj El Bahri','برج البحري'),('16','El Marsa','المرسى'),('16','Heraoua','هراوة'),('16','Rouiba','الرويبة'),('16','Reghaia','الرغاية'),('16','Ain Benian','عين البنيان'),('16','Staoueli','سطاوالي'),('16','Zeralda','زرالدة'),('16','Mahelma','محالمة'),('16','Rahmania','الرحمانية'),('16','Souidania','السويدانية'),('16','Cheraga','الشراقة'),('16','Ouled Fayet','أولاد فايت'),('16','El Achour','العاشور'),('16','Draria','درارية'),('16','Douera','الدويرة'),('16','Baba Hassen','بابا حسن'),('16','Khraicia','الخرايسية'),('16','Saoula','السحاولة'),
('31','Oran','وهران'),('31','Gdyel','قديل'),('31','Bir El Djir','بئر الجير'),('31','Hassi Bounif','حاسي بونيف'),('31','Es Senia','السانية'),('31','Arzew','أرزيو'),('31','Bethioua','بطيوة'),('31','Marsat El Hadjadj','مرسى الحجاج'),('31','Ain El Turk','عين الترك'),('31','El Ancor','العنصر'),('31','Oued Tlelat','وادي تليلات'),('31','Tafraoui','طفراوي'),('31','Sidi Chami','سيدي الشحمي'),('31','Boufatis','بوفاطيس'),('31','Mers El Kebir','المرسى الكبير'),('31','Bousfer','بوسفر'),('31','El Kerma','الكرمة'),('31','El Braya','البراية'),('31','Hassi Ben Okba','حاسي بن عقبة'),('31','Ben Freha','بن فريحة'),('31','Hassi Mefsoukh','حاسي مفسوخ'),('31','Sidi Ben Yebka','سيدي بن يبقى'),('31','Misserghin','مسرغين'),('31','Boutlelis','بوتليليس'),('31','Ain Kerma','عين الكرمة'),('31','Ain Biya','عين البية'),
('25','Constantine','قسنطينة'),('25','Hamma Bouziane','حامة بوزيان'),('25','El Khroub','الخروب'),('25','Ain Abid','عين عبيد'),('25','Zighoud Youcef','زيغود يوسف'),('25','Didouche Mourad','ديدوش مراد'),('25','El Haria','الحرية'),('25','Ain Smara','عين سمارة'),('25','Ouled Rahmoune','أولاد رحمون'),('25','Ibn Ziad','ابن زياد'),('25','Beni Hamidane','بني حميدان'),('25','Messaoud Boudjeriou','مسعود بوجريو'),
('23','Annaba','عنابة'),('23','Berrahal','برحال'),('23','El Hadjar','الحجار'),('23','Eulma','العلمة'),('23','El Bouni','البوني'),('23','Oued El Aneb','وادي العنب'),('23','Cheurfa','الشرفة'),('23','Seraidi','سرايدي'),('23','Ain Berda','عين الباردة'),('23','Chetaibi','شطايبي'),('23','Sidi Amar','سيدي عمار'),('23','Treat','التريعات'),
('02','Chlef','الشلف'),('02','Tenes','تنس'),('02','Benairia','بنايرية'),('02','El Karimia','الكريمية'),('02','Tadjena','تاجنة'),('02','Taougrite','تاوقريت'),('02','Beni Haoua','بني حواء'),('02','Sobha','الصبحة'),('02','Harchoun','حرشون'),('02','Ouled Fares','أولاد فارس'),('02','Sidi Akkacha','سيدي عكاشة'),('02','Boukadir','بوقادير'),('02','Beni Rached','بني راشد'),('02','Talassa','تلعصة'),('02','Herenfa','الهرانفة'),('02','Oued Goussine','وادي قوسين'),('02','Dahra','الظهرة'),('02','Ouled Abbes','أولاد عباس'),('02','Sendjas','سنجاس'),('02','Zeboudja','الزبوجة'),('02','Oued Sly','وادي سلي'),('02','Abou El Hassan','أبو الحسن'),('02','El Marsa','المرسى'),('02','Chettia','الشطية'),('02','Sidi Abderrahmane','سيدي عبد الرحمن'),('02','Moussadek','مصدق'),('02','El Hadjadj','الحجاج'),('02','Labiod Medjadja','الأبيض مجاجة'),('02','Oued Fodda','وادي الفضة'),('02','Ouled Ben Abdelkader','أولاد بن عبد القادر'),('02','Bouzeghaia','بوزغاية'),('02','Ain Merane','عين مران'),('02','Oum Drou','أم الدروع'),('02','Breira','بريرة'),('02','Beni Bouattab','بني بوعتاب')
),
todo AS (
  SELECT w.id AS wid, n.name_fr, n.name_ar,
         n.wcode || lpad((mx.m + row_number() OVER (PARTITION BY w.id ORDER BY n.name_fr))::text, 2, '0') AS code
  FROM new_b n
  JOIN public.wilayas w ON w.code = n.wcode
  LEFT JOIN LATERAL (
    SELECT COALESCE(MAX(RIGHT(b.code, 2)::int), 0) AS m FROM public.baladiyas b WHERE b.wilaya_id = w.id
  ) mx ON true
  WHERE NOT EXISTS (
    SELECT 1 FROM public.baladiyas b WHERE b.wilaya_id = w.id AND b.name_fr = n.name_fr
  )
)
INSERT INTO public.baladiyas (wilaya_id, code, name_ar, name_fr, name_en)
SELECT wid, code, name_ar, name_fr, name_fr FROM todo
WHERE NOT EXISTS (SELECT 1 FROM public.baladiyas b2 WHERE b2.code = todo.code);